### ISSUE TITLE
Where does qbrt store its profile?

### ISSUE THREAD

**Issue by benfrancis** [mozilla/qbrt#87]
Where does the qbrt runtime store its profile?

I'm trying to delete an IndexedDB database created from chrome but apparently DevTools doesn't like IndexedDB databases owned by chrome so I'm unable to delete it that way. I realised I don't know where qbrt stores its profile.

I couldn't find it in node_modules/ and I couldn't tell whether anything in ~/.mozilla/ belonged to qbrt. Does it share a profile with Firefox?!

**Comment by mykmelez** [comment]
For a session started by the *run* command, qbrt creates a temporary profile for the duration of the session and then deletes it. In order to support testing that requires profile persistence, qbrt should allow you to specify a profile directory to use when running an app. I filed that as issue #88.

For a session started by an app that was packaged with the *package* command, the runtime should use a platform-specific directory determined by the name of the app, as specified in the xulapp's application.ini file. However, currently qbrt doesn't change the name of the app in the xulapp's application.ini file, which is `qbrt` by default; so all packaged apps share the same profile directory. That's issue #78.

**Comment by benfrancis** [comment]
I think that answers my question, thanks. And explains why my IndexedDB database keeps getting recreated every time I start up! The bugs you filed sounds like good ideas.
